-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Galois_LFSR_32_33_hw is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC );
end;


architecture behav of Galois_LFSR_32_33_hw is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv33_F0F0 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000001111000011110000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv33_194000000 : STD_LOGIC_VECTOR (32 downto 0) := "110010100000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal guard_variable_for_G : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal lfsr33_V : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000000";
    signal select_ln21_fu_54_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal select_ln12_fu_22_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal lshr_ln_fu_34_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln858_fu_44_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal lsb33_V_fu_30_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln719_fu_48_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    guard_variable_for_G_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                lfsr33_V <= select_ln21_fu_54_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    lsb33_V_fu_30_p1 <= select_ln12_fu_22_p3(1 - 1 downto 0);
    lshr_ln_fu_34_p4 <= select_ln12_fu_22_p3(32 downto 1);
    select_ln12_fu_22_p3 <= 
        lfsr33_V when (guard_variable_for_G(0) = '1') else 
        ap_const_lv33_F0F0;
    select_ln21_fu_54_p3 <= 
        xor_ln719_fu_48_p2 when (lsb33_V_fu_30_p1(0) = '1') else 
        zext_ln858_fu_44_p1;
    xor_ln719_fu_48_p2 <= (zext_ln858_fu_44_p1 xor ap_const_lv33_194000000);
    zext_ln858_fu_44_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_34_p4),33));
end behav;
