// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "QIO_int_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic QIO_int_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic QIO_int_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<27> QIO_int_s::ap_ST_fsm_state1 = "1";
const sc_lv<27> QIO_int_s::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state4 = "100";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state5 = "1000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state6 = "10000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state7 = "100000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state8 = "1000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state9 = "10000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state10 = "100000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state11 = "1000000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state12 = "10000000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state13 = "100000000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state14 = "1000000000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state15 = "10000000000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state16 = "100000000000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state17 = "1000000000000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state18 = "10000000000000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state19 = "100000000000000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state20 = "1000000000000000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state21 = "10000000000000000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state22 = "100000000000000000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_pp1_stage0 = "1000000000000000000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_pp1_stage1 = "10000000000000000000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_pp1_stage2 = "100000000000000000000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_pp1_stage3 = "1000000000000000000000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_pp1_stage4 = "10000000000000000000000000";
const sc_lv<27> QIO_int_s::ap_ST_fsm_state45 = "100000000000000000000000000";
const bool QIO_int_s::ap_const_boolean_1 = true;
const sc_lv<32> QIO_int_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> QIO_int_s::ap_const_lv32_A = "1010";
const sc_lv<32> QIO_int_s::ap_const_lv32_16 = "10110";
const bool QIO_int_s::ap_const_boolean_0 = false;
const sc_lv<1> QIO_int_s::ap_const_lv1_0 = "0";
const sc_lv<32> QIO_int_s::ap_const_lv32_E = "1110";
const sc_lv<32> QIO_int_s::ap_const_lv32_F = "1111";
const sc_lv<32> QIO_int_s::ap_const_lv32_13 = "10011";
const sc_lv<32> QIO_int_s::ap_const_lv32_15 = "10101";
const sc_lv<32> QIO_int_s::ap_const_lv32_1 = "1";
const sc_lv<32> QIO_int_s::ap_const_lv32_3 = "11";
const sc_lv<32> QIO_int_s::ap_const_lv32_4 = "100";
const sc_lv<32> QIO_int_s::ap_const_lv32_9 = "1001";
const sc_lv<32> QIO_int_s::ap_const_lv32_14 = "10100";
const sc_lv<32> QIO_int_s::ap_const_lv32_17 = "10111";
const sc_lv<1> QIO_int_s::ap_const_lv1_1 = "1";
const sc_lv<32> QIO_int_s::ap_const_lv32_19 = "11001";
const sc_lv<7> QIO_int_s::ap_const_lv7_0 = "0000000";
const sc_lv<32> QIO_int_s::ap_const_lv32_1A = "11010";
const sc_lv<32> QIO_int_s::ap_const_lv32_2 = "10";
const sc_lv<32> QIO_int_s::ap_const_lv32_B = "1011";
const sc_lv<32> QIO_int_s::ap_const_lv32_18 = "11000";
const sc_lv<32> QIO_int_s::ap_const_lv32_5 = "101";
const sc_lv<7> QIO_int_s::ap_const_lv7_40 = "1000000";
const sc_lv<7> QIO_int_s::ap_const_lv7_1 = "1";
const sc_lv<6> QIO_int_s::ap_const_lv6_0 = "000000";
const sc_lv<32> QIO_int_s::ap_const_lv32_3F = "111111";

QIO_int_s::QIO_int_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    current_val2_U = new QIO_int_s_currentbkb("current_val2_U");
    current_val2_U->clk(ap_clk);
    current_val2_U->reset(ap_rst);
    current_val2_U->address0(current_val2_address0);
    current_val2_U->ce0(current_val2_ce0);
    current_val2_U->we0(current_val2_we0);
    current_val2_U->d0(current_val_q0);
    current_val2_U->q0(current_val2_q0);
    QIO_accel_fadd_32cud_U2 = new QIO_accel_fadd_32cud<1,5,32,32,32>("QIO_accel_fadd_32cud_U2");
    QIO_accel_fadd_32cud_U2->clk(ap_clk);
    QIO_accel_fadd_32cud_U2->reset(ap_rst);
    QIO_accel_fadd_32cud_U2->din0(grp_load_fu_163_p1);
    QIO_accel_fadd_32cud_U2->din1(grp_fu_152_p1);
    QIO_accel_fadd_32cud_U2->ce(ap_var_for_const0);
    QIO_accel_fadd_32cud_U2->dout(grp_fu_152_p2);
    QIO_accel_fmul_32dEe_U3 = new QIO_accel_fmul_32dEe<1,4,32,32,32>("QIO_accel_fmul_32dEe_U3");
    QIO_accel_fmul_32dEe_U3->clk(ap_clk);
    QIO_accel_fmul_32dEe_U3->reset(ap_rst);
    QIO_accel_fmul_32dEe_U3->din0(grp_fu_156_p0);
    QIO_accel_fmul_32dEe_U3->din1(grp_fu_156_p1);
    QIO_accel_fmul_32dEe_U3->ce(ap_var_for_const0);
    QIO_accel_fmul_32dEe_U3->dout(grp_fu_156_p2);
    QIO_accel_sitofp_eOg_U4 = new QIO_accel_sitofp_eOg<1,6,32,32>("QIO_accel_sitofp_eOg_U4");
    QIO_accel_sitofp_eOg_U4->clk(ap_clk);
    QIO_accel_sitofp_eOg_U4->reset(ap_rst);
    QIO_accel_sitofp_eOg_U4->din0(grp_fu_160_p0);
    QIO_accel_sitofp_eOg_U4->ce(ap_var_for_const0);
    QIO_accel_sitofp_eOg_U4->dout(grp_fu_160_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln32_fu_247_p2);
    sensitive << ( zext_ln32_2_fu_243_p1 );
    sensitive << ( zext_ln32_1_fu_231_p1 );

    SC_METHOD(thread_add_ln36_fu_283_p2);
    sensitive << ( zext_ln32_2_reg_336 );
    sensitive << ( trunc_ln36_fu_279_p1 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state45);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_11001);

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);

    SC_METHOD(thread_ap_block_pp1_stage1);

    SC_METHOD(thread_ap_block_pp1_stage1_11001);

    SC_METHOD(thread_ap_block_pp1_stage1_subdone);

    SC_METHOD(thread_ap_block_pp1_stage2);

    SC_METHOD(thread_ap_block_pp1_stage2_11001);

    SC_METHOD(thread_ap_block_pp1_stage2_subdone);

    SC_METHOD(thread_ap_block_pp1_stage3);

    SC_METHOD(thread_ap_block_pp1_stage3_subdone);

    SC_METHOD(thread_ap_block_pp1_stage4_subdone);

    SC_METHOD(thread_ap_block_state23_pp1_stage0_iter0);

    SC_METHOD(thread_ap_block_state24_pp1_stage1_iter0);

    SC_METHOD(thread_ap_block_state25_pp1_stage2_iter0);

    SC_METHOD(thread_ap_block_state26_pp1_stage3_iter0);

    SC_METHOD(thread_ap_block_state27_pp1_stage4_iter0);

    SC_METHOD(thread_ap_block_state28_pp1_stage0_iter1);

    SC_METHOD(thread_ap_block_state29_pp1_stage1_iter1);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state30_pp1_stage2_iter1);

    SC_METHOD(thread_ap_block_state31_pp1_stage3_iter1);

    SC_METHOD(thread_ap_block_state32_pp1_stage4_iter1);

    SC_METHOD(thread_ap_block_state33_pp1_stage0_iter2);

    SC_METHOD(thread_ap_block_state34_pp1_stage1_iter2);

    SC_METHOD(thread_ap_block_state35_pp1_stage2_iter2);

    SC_METHOD(thread_ap_block_state36_pp1_stage3_iter2);

    SC_METHOD(thread_ap_block_state37_pp1_stage4_iter2);

    SC_METHOD(thread_ap_block_state38_pp1_stage0_iter3);

    SC_METHOD(thread_ap_block_state39_pp1_stage1_iter3);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state40_pp1_stage2_iter3);

    SC_METHOD(thread_ap_block_state41_pp1_stage3_iter3);

    SC_METHOD(thread_ap_block_state42_pp1_stage4_iter3);

    SC_METHOD(thread_ap_block_state43_pp1_stage0_iter4);

    SC_METHOD(thread_ap_block_state44_pp1_stage1_iter4);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln26_fu_192_p2 );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state23);
    sensitive << ( icmp_ln34_fu_262_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln31_fu_214_p2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_enable_reg_pp1_iter3 );
    sensitive << ( ap_enable_reg_pp1_iter4 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_ap_phi_mux_j_0_in_phi_fu_146_p4);
    sensitive << ( j_0_in_reg_143 );
    sensitive << ( icmp_ln34_reg_356 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( j_reg_360 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln31_fu_214_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( grp_load_fu_163_p1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln31_fu_214_p2 );

    SC_METHOD(thread_ap_sig_allocacmp_cost_new_write_assig_2);
    sensitive << ( ap_CS_fsm_pp1_stage1 );
    sensitive << ( reg_183 );
    sensitive << ( ap_enable_reg_pp1_iter4 );
    sensitive << ( icmp_ln34_reg_356_pp1_iter4_reg );
    sensitive << ( cost_new_write_assig_fu_54 );
    sensitive << ( ap_block_pp1_stage1 );

    SC_METHOD(thread_coef_list_address0);
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( zext_ln32_3_fu_253_p1 );
    sensitive << ( sext_ln36_1_fu_288_p1 );

    SC_METHOD(thread_coef_list_ce0);
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_current_val2_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( zext_ln28_reg_301 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln36_fu_274_p1 );

    SC_METHOD(thread_current_val2_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_current_val2_we0);
    sensitive << ( icmp_ln26_reg_292 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_current_val_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( zext_ln28_fu_204_p1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln32_fu_226_p1 );

    SC_METHOD(thread_current_val_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_grp_fu_152_p1);
    sensitive << ( ap_CS_fsm_pp1_stage1 );
    sensitive << ( reg_172 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_enable_reg_pp1_iter3 );
    sensitive << ( tmp_4_reg_390 );
    sensitive << ( ap_block_pp1_stage1 );

    SC_METHOD(thread_grp_fu_156_p0);
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( reg_172 );
    sensitive << ( tmp_reg_346 );
    sensitive << ( ap_CS_fsm_pp1_stage2 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_pp1_stage3 );
    sensitive << ( ap_block_pp1_stage3 );
    sensitive << ( ap_block_pp1_stage2 );

    SC_METHOD(thread_grp_fu_156_p1);
    sensitive << ( reg_167 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( tmp_2_reg_380 );
    sensitive << ( ap_CS_fsm_pp1_stage2 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_pp1_stage3 );
    sensitive << ( ap_block_pp1_stage3 );
    sensitive << ( ap_block_pp1_stage2 );

    SC_METHOD(thread_grp_fu_160_p0);
    sensitive << ( current_val_load_2_reg_331 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( current_val2_load_reg_375 );
    sensitive << ( ap_CS_fsm_pp1_stage2 );
    sensitive << ( ap_block_pp1_stage2 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_grp_load_fu_163_p1);
    sensitive << ( ap_CS_fsm_pp1_stage1 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_enable_reg_pp1_iter3 );
    sensitive << ( icmp_ln34_reg_356_pp1_iter3_reg );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln31_fu_214_p2 );
    sensitive << ( cost_new_write_assig_fu_54 );
    sensitive << ( ap_sig_allocacmp_cost_new_write_assig_2 );
    sensitive << ( ap_block_pp1_stage1 );

    SC_METHOD(thread_i_6_fu_220_p2);
    sensitive << ( i1_0_reg_131 );

    SC_METHOD(thread_i_fu_198_p2);
    sensitive << ( i_0_reg_120 );

    SC_METHOD(thread_icmp_ln26_fu_192_p2);
    sensitive << ( i_0_reg_120 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln31_fu_214_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i1_0_reg_131 );

    SC_METHOD(thread_icmp_ln34_fu_262_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_phi_mux_j_0_in_phi_fu_146_p4 );

    SC_METHOD(thread_j_fu_268_p2);
    sensitive << ( ap_phi_mux_j_0_in_phi_fu_146_p4 );

    SC_METHOD(thread_sext_ln36_1_fu_288_p1);
    sensitive << ( add_ln36_reg_365_pp1_iter1_reg );

    SC_METHOD(thread_sext_ln36_fu_274_p1);
    sensitive << ( j_fu_268_p2 );

    SC_METHOD(thread_tmp_1_fu_235_p3);
    sensitive << ( i1_0_reg_131 );

    SC_METHOD(thread_trunc_ln36_fu_279_p1);
    sensitive << ( j_fu_268_p2 );

    SC_METHOD(thread_zext_ln28_fu_204_p1);
    sensitive << ( i_0_reg_120 );

    SC_METHOD(thread_zext_ln31_fu_258_p1);
    sensitive << ( i1_0_reg_131 );

    SC_METHOD(thread_zext_ln32_1_fu_231_p1);
    sensitive << ( i1_0_reg_131 );

    SC_METHOD(thread_zext_ln32_2_fu_243_p1);
    sensitive << ( tmp_1_fu_235_p3 );

    SC_METHOD(thread_zext_ln32_3_fu_253_p1);
    sensitive << ( add_ln32_fu_247_p2 );

    SC_METHOD(thread_zext_ln32_fu_226_p1);
    sensitive << ( i1_0_reg_131 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_pp1_stage1 );
    sensitive << ( ap_enable_reg_pp1_iter3 );
    sensitive << ( ap_enable_reg_pp1_iter4 );
    sensitive << ( icmp_ln26_fu_192_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln31_fu_214_p2 );
    sensitive << ( icmp_ln34_fu_262_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp1_stage0_subdone );
    sensitive << ( ap_block_pp1_stage4_subdone );
    sensitive << ( ap_block_pp1_stage1_subdone );
    sensitive << ( ap_block_pp1_stage2_subdone );
    sensitive << ( ap_block_pp1_stage3_subdone );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000000000000000000001";
    ap_enable_reg_pp1_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "QIO_int_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, current_val_address0, "(port)current_val_address0");
    sc_trace(mVcdFile, current_val_ce0, "(port)current_val_ce0");
    sc_trace(mVcdFile, current_val_q0, "(port)current_val_q0");
    sc_trace(mVcdFile, coef_list_address0, "(port)coef_list_address0");
    sc_trace(mVcdFile, coef_list_ce0, "(port)coef_list_ce0");
    sc_trace(mVcdFile, coef_list_q0, "(port)coef_list_q0");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_0_reg_120, "i_0_reg_120");
    sc_trace(mVcdFile, j_0_in_reg_143, "j_0_in_reg_143");
    sc_trace(mVcdFile, reg_167, "reg_167");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage1, "ap_CS_fsm_pp1_stage1");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter2, "ap_enable_reg_pp1_iter2");
    sc_trace(mVcdFile, ap_block_state24_pp1_stage1_iter0, "ap_block_state24_pp1_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state29_pp1_stage1_iter1, "ap_block_state29_pp1_stage1_iter1");
    sc_trace(mVcdFile, ap_block_state34_pp1_stage1_iter2, "ap_block_state34_pp1_stage1_iter2");
    sc_trace(mVcdFile, ap_block_state39_pp1_stage1_iter3, "ap_block_state39_pp1_stage1_iter3");
    sc_trace(mVcdFile, ap_block_state44_pp1_stage1_iter4, "ap_block_state44_pp1_stage1_iter4");
    sc_trace(mVcdFile, ap_block_pp1_stage1_11001, "ap_block_pp1_stage1_11001");
    sc_trace(mVcdFile, icmp_ln34_reg_356, "icmp_ln34_reg_356");
    sc_trace(mVcdFile, icmp_ln34_reg_356_pp1_iter2_reg, "icmp_ln34_reg_356_pp1_iter2_reg");
    sc_trace(mVcdFile, grp_fu_156_p2, "grp_fu_156_p2");
    sc_trace(mVcdFile, reg_172, "reg_172");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, grp_load_fu_163_p1, "grp_load_fu_163_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter3, "ap_enable_reg_pp1_iter3");
    sc_trace(mVcdFile, icmp_ln34_reg_356_pp1_iter3_reg, "icmp_ln34_reg_356_pp1_iter3_reg");
    sc_trace(mVcdFile, grp_fu_152_p2, "grp_fu_152_p2");
    sc_trace(mVcdFile, reg_183, "reg_183");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter4, "ap_enable_reg_pp1_iter4");
    sc_trace(mVcdFile, ap_block_state23_pp1_stage0_iter0, "ap_block_state23_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state28_pp1_stage0_iter1, "ap_block_state28_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state33_pp1_stage0_iter2, "ap_block_state33_pp1_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state38_pp1_stage0_iter3, "ap_block_state38_pp1_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state43_pp1_stage0_iter4, "ap_block_state43_pp1_stage0_iter4");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, icmp_ln26_fu_192_p2, "icmp_ln26_fu_192_p2");
    sc_trace(mVcdFile, icmp_ln26_reg_292, "icmp_ln26_reg_292");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_fu_198_p2, "i_fu_198_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, zext_ln28_fu_204_p1, "zext_ln28_fu_204_p1");
    sc_trace(mVcdFile, zext_ln28_reg_301, "zext_ln28_reg_301");
    sc_trace(mVcdFile, i_6_fu_220_p2, "i_6_fu_220_p2");
    sc_trace(mVcdFile, i_6_reg_321, "i_6_reg_321");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, icmp_ln31_fu_214_p2, "icmp_ln31_fu_214_p2");
    sc_trace(mVcdFile, current_val_load_2_reg_331, "current_val_load_2_reg_331");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, zext_ln32_2_fu_243_p1, "zext_ln32_2_fu_243_p1");
    sc_trace(mVcdFile, zext_ln32_2_reg_336, "zext_ln32_2_reg_336");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, grp_fu_160_p1, "grp_fu_160_p1");
    sc_trace(mVcdFile, tmp_reg_346, "tmp_reg_346");
    sc_trace(mVcdFile, zext_ln31_fu_258_p1, "zext_ln31_fu_258_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, icmp_ln34_fu_262_p2, "icmp_ln34_fu_262_p2");
    sc_trace(mVcdFile, icmp_ln34_reg_356_pp1_iter1_reg, "icmp_ln34_reg_356_pp1_iter1_reg");
    sc_trace(mVcdFile, icmp_ln34_reg_356_pp1_iter4_reg, "icmp_ln34_reg_356_pp1_iter4_reg");
    sc_trace(mVcdFile, j_fu_268_p2, "j_fu_268_p2");
    sc_trace(mVcdFile, j_reg_360, "j_reg_360");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, add_ln36_fu_283_p2, "add_ln36_fu_283_p2");
    sc_trace(mVcdFile, add_ln36_reg_365, "add_ln36_reg_365");
    sc_trace(mVcdFile, add_ln36_reg_365_pp1_iter1_reg, "add_ln36_reg_365_pp1_iter1_reg");
    sc_trace(mVcdFile, current_val2_q0, "current_val2_q0");
    sc_trace(mVcdFile, current_val2_load_reg_375, "current_val2_load_reg_375");
    sc_trace(mVcdFile, tmp_2_reg_380, "tmp_2_reg_380");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage2, "ap_CS_fsm_pp1_stage2");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, ap_block_state25_pp1_stage2_iter0, "ap_block_state25_pp1_stage2_iter0");
    sc_trace(mVcdFile, ap_block_state30_pp1_stage2_iter1, "ap_block_state30_pp1_stage2_iter1");
    sc_trace(mVcdFile, ap_block_state35_pp1_stage2_iter2, "ap_block_state35_pp1_stage2_iter2");
    sc_trace(mVcdFile, ap_block_state40_pp1_stage2_iter3, "ap_block_state40_pp1_stage2_iter3");
    sc_trace(mVcdFile, ap_block_pp1_stage2_11001, "ap_block_pp1_stage2_11001");
    sc_trace(mVcdFile, tmp_4_reg_390, "tmp_4_reg_390");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state23, "ap_condition_pp1_exit_iter0_state23");
    sc_trace(mVcdFile, ap_block_state27_pp1_stage4_iter0, "ap_block_state27_pp1_stage4_iter0");
    sc_trace(mVcdFile, ap_block_state32_pp1_stage4_iter1, "ap_block_state32_pp1_stage4_iter1");
    sc_trace(mVcdFile, ap_block_state37_pp1_stage4_iter2, "ap_block_state37_pp1_stage4_iter2");
    sc_trace(mVcdFile, ap_block_state42_pp1_stage4_iter3, "ap_block_state42_pp1_stage4_iter3");
    sc_trace(mVcdFile, ap_block_pp1_stage4_subdone, "ap_block_pp1_stage4_subdone");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage4, "ap_CS_fsm_pp1_stage4");
    sc_trace(mVcdFile, ap_block_pp1_stage1_subdone, "ap_block_pp1_stage1_subdone");
    sc_trace(mVcdFile, current_val2_address0, "current_val2_address0");
    sc_trace(mVcdFile, current_val2_ce0, "current_val2_ce0");
    sc_trace(mVcdFile, current_val2_we0, "current_val2_we0");
    sc_trace(mVcdFile, i1_0_reg_131, "i1_0_reg_131");
    sc_trace(mVcdFile, ap_CS_fsm_state45, "ap_CS_fsm_state45");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_phi_mux_j_0_in_phi_fu_146_p4, "ap_phi_mux_j_0_in_phi_fu_146_p4");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, zext_ln32_fu_226_p1, "zext_ln32_fu_226_p1");
    sc_trace(mVcdFile, zext_ln32_3_fu_253_p1, "zext_ln32_3_fu_253_p1");
    sc_trace(mVcdFile, sext_ln36_fu_274_p1, "sext_ln36_fu_274_p1");
    sc_trace(mVcdFile, sext_ln36_1_fu_288_p1, "sext_ln36_1_fu_288_p1");
    sc_trace(mVcdFile, cost_new_write_assig_fu_54, "cost_new_write_assig_fu_54");
    sc_trace(mVcdFile, ap_sig_allocacmp_cost_new_write_assig_2, "ap_sig_allocacmp_cost_new_write_assig_2");
    sc_trace(mVcdFile, ap_block_pp1_stage1, "ap_block_pp1_stage1");
    sc_trace(mVcdFile, grp_fu_152_p1, "grp_fu_152_p1");
    sc_trace(mVcdFile, grp_fu_156_p0, "grp_fu_156_p0");
    sc_trace(mVcdFile, grp_fu_156_p1, "grp_fu_156_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage3, "ap_CS_fsm_pp1_stage3");
    sc_trace(mVcdFile, ap_block_pp1_stage3, "ap_block_pp1_stage3");
    sc_trace(mVcdFile, ap_block_pp1_stage2, "ap_block_pp1_stage2");
    sc_trace(mVcdFile, grp_fu_160_p0, "grp_fu_160_p0");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_1_fu_235_p3, "tmp_1_fu_235_p3");
    sc_trace(mVcdFile, zext_ln32_1_fu_231_p1, "zext_ln32_1_fu_231_p1");
    sc_trace(mVcdFile, add_ln32_fu_247_p2, "add_ln32_fu_247_p2");
    sc_trace(mVcdFile, trunc_ln36_fu_279_p1, "trunc_ln36_fu_279_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_block_pp1_stage2_subdone, "ap_block_pp1_stage2_subdone");
    sc_trace(mVcdFile, ap_block_state26_pp1_stage3_iter0, "ap_block_state26_pp1_stage3_iter0");
    sc_trace(mVcdFile, ap_block_state31_pp1_stage3_iter1, "ap_block_state31_pp1_stage3_iter1");
    sc_trace(mVcdFile, ap_block_state36_pp1_stage3_iter2, "ap_block_state36_pp1_stage3_iter2");
    sc_trace(mVcdFile, ap_block_state41_pp1_stage3_iter3, "ap_block_state41_pp1_stage3_iter3");
    sc_trace(mVcdFile, ap_block_pp1_stage3_subdone, "ap_block_pp1_stage3_subdone");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
#endif

    }
}

QIO_int_s::~QIO_int_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete current_val2_U;
    delete QIO_accel_fadd_32cud_U2;
    delete QIO_accel_fmul_32dEe_U3;
    delete QIO_accel_sitofp_eOg_U4;
}

void QIO_int_s::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void QIO_int_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state23.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp1_stage4_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage4.read()))) {
            ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter2 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp1_stage4_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage4.read()))) {
            ap_enable_reg_pp1_iter2 = ap_enable_reg_pp1_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter3 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp1_stage4_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage4.read()))) {
            ap_enable_reg_pp1_iter3 = ap_enable_reg_pp1_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter4 = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_block_pp1_stage4_subdone.read(), ap_const_boolean_0) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage4.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && 
              esl_seteq<1,1,1>(ap_block_pp1_stage1_subdone.read(), ap_const_boolean_0)))) {
            ap_enable_reg_pp1_iter4 = ap_enable_reg_pp1_iter3.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
            ap_enable_reg_pp1_iter4 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage1_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln34_reg_356_pp1_iter4_reg.read())))) {
        cost_new_write_assig_fu_54 = reg_183.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        cost_new_write_assig_fu_54 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i1_0_reg_131 = ap_const_lv7_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state45.read())) {
        i1_0_reg_131 = i_6_reg_321.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln26_fu_192_p2.read()))) {
        i_0_reg_120 = i_fu_198_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_120 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln34_reg_356.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()))) {
        j_0_in_reg_143 = j_reg_360.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        j_0_in_reg_143 = zext_ln31_fu_258_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln34_fu_262_p2.read()))) {
        add_ln36_reg_365 = add_ln36_fu_283_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        add_ln36_reg_365_pp1_iter1_reg = add_ln36_reg_365.read();
        icmp_ln34_reg_356 = icmp_ln34_fu_262_p2.read();
        icmp_ln34_reg_356_pp1_iter1_reg = icmp_ln34_reg_356.read();
        icmp_ln34_reg_356_pp1_iter2_reg = icmp_ln34_reg_356_pp1_iter1_reg.read();
        icmp_ln34_reg_356_pp1_iter3_reg = icmp_ln34_reg_356_pp1_iter2_reg.read();
        icmp_ln34_reg_356_pp1_iter4_reg = icmp_ln34_reg_356_pp1_iter3_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(icmp_ln34_reg_356.read(), ap_const_lv1_0))) {
        current_val2_load_reg_375 = current_val2_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        current_val_load_2_reg_331 = current_val_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_6_reg_321 = i_6_fu_220_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln26_reg_292 = icmp_ln26_fu_192_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln34_fu_262_p2.read()))) {
        j_reg_360 = j_fu_268_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
  esl_seteq<1,1,1>(ap_block_pp1_stage1_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln34_reg_356_pp1_iter2_reg.read(), ap_const_lv1_0)))) {
        reg_167 = coef_list_q0.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
  esl_seteq<1,1,1>(ap_block_pp1_stage1_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln34_reg_356_pp1_iter2_reg.read(), ap_const_lv1_0)) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        reg_172 = grp_fu_156_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) || (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln34_reg_356_pp1_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter4.read()) && 
  esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)))) {
        reg_183 = grp_fu_152_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage2.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage2_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln34_reg_356_pp1_iter1_reg.read()))) {
        tmp_2_reg_380 = grp_fu_160_p1.read();
    }
    if ((esl_seteq<1,1,1>(icmp_ln34_reg_356_pp1_iter2_reg.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter3.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_4_reg_390 = grp_fu_156_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        tmp_reg_346 = grp_fu_160_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln26_fu_192_p2.read()))) {
        zext_ln28_reg_301 = zext_ln28_fu_204_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        zext_ln32_2_reg_336 = zext_ln32_2_fu_243_p1.read();
    }
}

void QIO_int_s::thread_add_ln32_fu_247_p2() {
    add_ln32_fu_247_p2 = (!zext_ln32_1_fu_231_p1.read().is_01() || !zext_ln32_2_fu_243_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(zext_ln32_1_fu_231_p1.read()) + sc_biguint<14>(zext_ln32_2_fu_243_p1.read()));
}

void QIO_int_s::thread_add_ln36_fu_283_p2() {
    add_ln36_fu_283_p2 = (!zext_ln32_2_reg_336.read().is_01() || !trunc_ln36_fu_279_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(zext_ln32_2_reg_336.read()) + sc_biguint<14>(trunc_ln36_fu_279_p1.read()));
}

void QIO_int_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void QIO_int_s::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[21];
}

void QIO_int_s::thread_ap_CS_fsm_pp1_stage1() {
    ap_CS_fsm_pp1_stage1 = ap_CS_fsm.read()[22];
}

void QIO_int_s::thread_ap_CS_fsm_pp1_stage2() {
    ap_CS_fsm_pp1_stage2 = ap_CS_fsm.read()[23];
}

void QIO_int_s::thread_ap_CS_fsm_pp1_stage3() {
    ap_CS_fsm_pp1_stage3 = ap_CS_fsm.read()[24];
}

void QIO_int_s::thread_ap_CS_fsm_pp1_stage4() {
    ap_CS_fsm_pp1_stage4 = ap_CS_fsm.read()[25];
}

void QIO_int_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void QIO_int_s::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[9];
}

void QIO_int_s::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[10];
}

void QIO_int_s::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[11];
}

void QIO_int_s::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[14];
}

void QIO_int_s::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[15];
}

void QIO_int_s::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[19];
}

void QIO_int_s::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[20];
}

void QIO_int_s::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[2];
}

void QIO_int_s::thread_ap_CS_fsm_state45() {
    ap_CS_fsm_state45 = ap_CS_fsm.read()[26];
}

void QIO_int_s::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[3];
}

void QIO_int_s::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[4];
}

void QIO_int_s::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[5];
}

void QIO_int_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_pp1_stage1() {
    ap_block_pp1_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_pp1_stage1_11001() {
    ap_block_pp1_stage1_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_pp1_stage1_subdone() {
    ap_block_pp1_stage1_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_pp1_stage2() {
    ap_block_pp1_stage2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_pp1_stage2_11001() {
    ap_block_pp1_stage2_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_pp1_stage2_subdone() {
    ap_block_pp1_stage2_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_pp1_stage3() {
    ap_block_pp1_stage3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_pp1_stage3_subdone() {
    ap_block_pp1_stage3_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_pp1_stage4_subdone() {
    ap_block_pp1_stage4_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state23_pp1_stage0_iter0() {
    ap_block_state23_pp1_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state24_pp1_stage1_iter0() {
    ap_block_state24_pp1_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state25_pp1_stage2_iter0() {
    ap_block_state25_pp1_stage2_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state26_pp1_stage3_iter0() {
    ap_block_state26_pp1_stage3_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state27_pp1_stage4_iter0() {
    ap_block_state27_pp1_stage4_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state28_pp1_stage0_iter1() {
    ap_block_state28_pp1_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state29_pp1_stage1_iter1() {
    ap_block_state29_pp1_stage1_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state30_pp1_stage2_iter1() {
    ap_block_state30_pp1_stage2_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state31_pp1_stage3_iter1() {
    ap_block_state31_pp1_stage3_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state32_pp1_stage4_iter1() {
    ap_block_state32_pp1_stage4_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state33_pp1_stage0_iter2() {
    ap_block_state33_pp1_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state34_pp1_stage1_iter2() {
    ap_block_state34_pp1_stage1_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state35_pp1_stage2_iter2() {
    ap_block_state35_pp1_stage2_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state36_pp1_stage3_iter2() {
    ap_block_state36_pp1_stage3_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state37_pp1_stage4_iter2() {
    ap_block_state37_pp1_stage4_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state38_pp1_stage0_iter3() {
    ap_block_state38_pp1_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state39_pp1_stage1_iter3() {
    ap_block_state39_pp1_stage1_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state40_pp1_stage2_iter3() {
    ap_block_state40_pp1_stage2_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state41_pp1_stage3_iter3() {
    ap_block_state41_pp1_stage3_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state42_pp1_stage4_iter3() {
    ap_block_state42_pp1_stage4_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state43_pp1_stage0_iter4() {
    ap_block_state43_pp1_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_block_state44_pp1_stage1_iter4() {
    ap_block_state44_pp1_stage1_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void QIO_int_s::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln26_fu_192_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void QIO_int_s::thread_ap_condition_pp1_exit_iter0_state23() {
    if (esl_seteq<1,1,1>(icmp_ln34_fu_262_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp1_exit_iter0_state23 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state23 = ap_const_logic_0;
    }
}

void QIO_int_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(icmp_ln31_fu_214_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void QIO_int_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void QIO_int_s::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void QIO_int_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void QIO_int_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void QIO_int_s::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter4.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void QIO_int_s::thread_ap_phi_mux_j_0_in_phi_fu_146_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln34_reg_356.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_j_0_in_phi_fu_146_p4 = j_reg_360.read();
    } else {
        ap_phi_mux_j_0_in_phi_fu_146_p4 = j_0_in_reg_143.read();
    }
}

void QIO_int_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln31_fu_214_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void QIO_int_s::thread_ap_return() {
    ap_return = grp_load_fu_163_p1.read();
}

void QIO_int_s::thread_ap_sig_allocacmp_cost_new_write_assig_2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln34_reg_356_pp1_iter4_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage1.read(), ap_const_boolean_0))) {
        ap_sig_allocacmp_cost_new_write_assig_2 = reg_183.read();
    } else {
        ap_sig_allocacmp_cost_new_write_assig_2 = cost_new_write_assig_fu_54.read();
    }
}

void QIO_int_s::thread_coef_list_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        coef_list_address0 =  (sc_lv<12>) (sext_ln36_1_fu_288_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        coef_list_address0 =  (sc_lv<12>) (zext_ln32_3_fu_253_p1.read());
    } else {
        coef_list_address0 = "XXXXXXXXXXXX";
    }
}

void QIO_int_s::thread_coef_list_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)))) {
        coef_list_ce0 = ap_const_logic_1;
    } else {
        coef_list_ce0 = ap_const_logic_0;
    }
}

void QIO_int_s::thread_current_val2_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        current_val2_address0 =  (sc_lv<6>) (sext_ln36_fu_274_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        current_val2_address0 =  (sc_lv<6>) (zext_ln28_reg_301.read());
    } else {
        current_val2_address0 =  (sc_lv<6>) ("XXXXXX");
    }
}

void QIO_int_s::thread_current_val2_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
        current_val2_ce0 = ap_const_logic_1;
    } else {
        current_val2_ce0 = ap_const_logic_0;
    }
}

void QIO_int_s::thread_current_val2_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln26_reg_292.read()))) {
        current_val2_we0 = ap_const_logic_1;
    } else {
        current_val2_we0 = ap_const_logic_0;
    }
}

void QIO_int_s::thread_current_val_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        current_val_address0 =  (sc_lv<6>) (zext_ln32_fu_226_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        current_val_address0 =  (sc_lv<6>) (zext_ln28_fu_204_p1.read());
    } else {
        current_val_address0 =  (sc_lv<6>) ("XXXXXX");
    }
}

void QIO_int_s::thread_current_val_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        current_val_ce0 = ap_const_logic_1;
    } else {
        current_val_ce0 = ap_const_logic_0;
    }
}

void QIO_int_s::thread_grp_fu_152_p1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter3.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage1.read(), ap_const_boolean_0))) {
        grp_fu_152_p1 = tmp_4_reg_390.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_152_p1 = reg_172.read();
    } else {
        grp_fu_152_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void QIO_int_s::thread_grp_fu_156_p0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage2.read(), ap_const_boolean_0))) {
        grp_fu_156_p0 = reg_172.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage3.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp1_stage3.read(), ap_const_boolean_0)))) {
        grp_fu_156_p0 = tmp_reg_346.read();
    } else {
        grp_fu_156_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void QIO_int_s::thread_grp_fu_156_p1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage3.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage3.read(), ap_const_boolean_0))) {
        grp_fu_156_p1 = tmp_2_reg_380.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage2.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp1_stage2.read(), ap_const_boolean_0)))) {
        grp_fu_156_p1 = reg_167.read();
    } else {
        grp_fu_156_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void QIO_int_s::thread_grp_fu_160_p0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage2.read(), ap_const_boolean_0))) {
        grp_fu_160_p0 = current_val2_load_reg_375.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        grp_fu_160_p0 = current_val_load_2_reg_331.read();
    } else {
        grp_fu_160_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void QIO_int_s::thread_grp_load_fu_163_p1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln34_reg_356_pp1_iter3_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage1.read(), ap_const_boolean_0))) {
        grp_load_fu_163_p1 = ap_sig_allocacmp_cost_new_write_assig_2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                 esl_seteq<1,1,1>(icmp_ln31_fu_214_p2.read(), ap_const_lv1_1)))) {
        grp_load_fu_163_p1 = cost_new_write_assig_fu_54.read();
    } else {
        grp_load_fu_163_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void QIO_int_s::thread_i_6_fu_220_p2() {
    i_6_fu_220_p2 = (!i1_0_reg_131.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i1_0_reg_131.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void QIO_int_s::thread_i_fu_198_p2() {
    i_fu_198_p2 = (!i_0_reg_120.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i_0_reg_120.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void QIO_int_s::thread_icmp_ln26_fu_192_p2() {
    icmp_ln26_fu_192_p2 = (!i_0_reg_120.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_120.read() == ap_const_lv7_40);
}

void QIO_int_s::thread_icmp_ln31_fu_214_p2() {
    icmp_ln31_fu_214_p2 = (!i1_0_reg_131.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(i1_0_reg_131.read() == ap_const_lv7_40);
}

void QIO_int_s::thread_icmp_ln34_fu_262_p2() {
    icmp_ln34_fu_262_p2 = (!ap_phi_mux_j_0_in_phi_fu_146_p4.read().is_01() || !ap_const_lv32_3F.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_j_0_in_phi_fu_146_p4.read() == ap_const_lv32_3F);
}

void QIO_int_s::thread_j_fu_268_p2() {
    j_fu_268_p2 = (!ap_const_lv32_1.is_01() || !ap_phi_mux_j_0_in_phi_fu_146_p4.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(ap_phi_mux_j_0_in_phi_fu_146_p4.read()));
}

void QIO_int_s::thread_sext_ln36_1_fu_288_p1() {
    sext_ln36_1_fu_288_p1 = esl_sext<64,14>(add_ln36_reg_365_pp1_iter1_reg.read());
}

void QIO_int_s::thread_sext_ln36_fu_274_p1() {
    sext_ln36_fu_274_p1 = esl_sext<64,32>(j_fu_268_p2.read());
}

void QIO_int_s::thread_tmp_1_fu_235_p3() {
    tmp_1_fu_235_p3 = esl_concat<7,6>(i1_0_reg_131.read(), ap_const_lv6_0);
}

void QIO_int_s::thread_trunc_ln36_fu_279_p1() {
    trunc_ln36_fu_279_p1 = j_fu_268_p2.read().range(14-1, 0);
}

void QIO_int_s::thread_zext_ln28_fu_204_p1() {
    zext_ln28_fu_204_p1 = esl_zext<64,7>(i_0_reg_120.read());
}

void QIO_int_s::thread_zext_ln31_fu_258_p1() {
    zext_ln31_fu_258_p1 = esl_zext<32,7>(i1_0_reg_131.read());
}

void QIO_int_s::thread_zext_ln32_1_fu_231_p1() {
    zext_ln32_1_fu_231_p1 = esl_zext<14,7>(i1_0_reg_131.read());
}

void QIO_int_s::thread_zext_ln32_2_fu_243_p1() {
    zext_ln32_2_fu_243_p1 = esl_zext<14,13>(tmp_1_fu_235_p3.read());
}

void QIO_int_s::thread_zext_ln32_3_fu_253_p1() {
    zext_ln32_3_fu_253_p1 = esl_zext<64,14>(add_ln32_fu_247_p2.read());
}

void QIO_int_s::thread_zext_ln32_fu_226_p1() {
    zext_ln32_fu_226_p1 = esl_zext<64,7>(i1_0_reg_131.read());
}

void QIO_int_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln26_fu_192_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln26_fu_192_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln31_fu_214_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            break;
        case 2097152 : 
            if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln34_fu_262_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln34_fu_262_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state45;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 4194304 : 
            if ((esl_seteq<1,1,1>(ap_block_pp1_stage1_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter4.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage1_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter3.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter4.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage1_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter3.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state45;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            }
            break;
        case 8388608 : 
            if (esl_seteq<1,1,1>(ap_block_pp1_stage2_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage3;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage2;
            }
            break;
        case 16777216 : 
            if (esl_seteq<1,1,1>(ap_block_pp1_stage3_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage3;
            }
            break;
        case 33554432 : 
            if (esl_seteq<1,1,1>(ap_block_pp1_stage4_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage4;
            }
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<27>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

